batch_size: 100
cluster_temperature: 1.0
dataset: ImageNet-10
dataset_dir: ./datasets
epochs: 1015
feature_dim: 128
image_size: 224
instance_temperature: 0.5
learning_rate: 0.0001
model_path: ./save/ImageNet-10
reload: true
resnet: ResNet34
seed: 42
start_epoch: 200
weight_decay: 0.0
workers: 4
